# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.4

# Site settings
title:              Kedai Resensi Surabaya
logo:               '\assets\krs-logo.png' # Logo image URL
description:        Resensi singkat dan segala macamnya
baseurl:            '' # The subpath of your site, e.g. /blog
url:                '' # The base hostname & protocol for your site
twitter:            https://twitter.com/rezafaricha
facebook:           https://www.facebook.com/kedairesensisurabaya
instagram:          https://www.instagram.com/rezafaricha

markdown:  kramdown
permalink: pretty
paginate:  16
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  krs:
    name:     Kedai Resensi Surabaya
    bio:      Resensi buku, jurnal, film, dan musik oleh dua orang pembaca dan kolektor buku. Berbasis di Surabaya.
    gravatar: https://s.gravatar.com/avatar/5098da732e6a13356c3a5e15cae323c0?s=150
    email:    kedairesensisurabaya@gmail.com
    website:  http://kedairesensisurabaya.net
    instagram: https://instagram.com/rezafaricha
  faricha:
    name:     A. Faricha Mantika
    bio:      Co-founder of KRS. Running a bookshop, KB. MURBA.
    gravatar: https://s.gravatar.com/avatar/5098da732e6a13356c3a5e15cae323c0?s=150
    email:    afmantika@outlook.com
    github:   https://github.com/faaaricha
    twitter:  https://twitter.com/rezafaricha
    instagram: https://instagram.com/rezafaricha
  reza:
    name:     Reza M. Hikam
    bio:      Founder of KRS. Running a bookshop, KB. MURBA.
    gravatar: https://s.gravatar.com/avatar/5098da732e6a13356c3a5e15cae323c0?s=150
    email:    rezahikam97@gmail.com
    twitter:  https://twitter.com/rezafaricha
    instagram: https://instagram.com/kbmurba
  dian:
    name:     Dian Dwi Jayanto
    bio:      Alumni S1 FISIP UNAIR, menempuh pendidikan S2 di FISIPOL UGM, dan pernah nyantri di Pondok Pesantren Bahrul Ulum Tambakberas Jombang.
    gravatar: https://s.gravatar.com/avatar/5098da732e6a13356c3a5e15cae323c0?s=150
    email:    dwijayanto_dian@yahoo.com
    twitter:  https://twitter.com/DianDjd
    instagram: https://www.instagram.com/diandwijayanto/